### ISSUE TITLE
IRQ callback invoked just once?

### ISSUE THREAD

**Issue by davidedelvento** [vmilea/pico_i2c_slave#3]
I am utilizing your library as you suggested in issue #2 namely

> Produce the data in your main loop, and consume it in the callback. If there's nothing ready to send yet, simply return from the callback and it will be invoked again. For producer-consumer scheme there's buffering and synchronization to deal with.

I am using `pico/util/queue.h` to pass the data from the main thread to the interrupt (I also experimented simply with volatile variables). The IRQ gets called without data being ready, and for my application this is a guarantee that will happen all the time, but for now I am just doing a test in which the data is not ready at the beginning. Based on what you wrote above, I expected that the callback would be automatically called a few more times, until the data was ready. Instead, the data gets prepared, but the IRQ callback is never called again, and everything comes to a stall.

I could make a dummy packet for these situations, but I really want to avoid that, since it's a lot of unnecessary traffic (and some additional code on both the sender and receiver side to deal with) which I really want to avoid. As such, can you please elaborate more on the "it will be invoked again" part? In what circumstances will that happen? Just making a single call to `i2c_read_blocking` on the controller side, and nothing else on the worker side, does not trigger that re-invocation, only a single invocation (from which I return as discussed above) and then a hang. Should I use timeouts on the controller and re-invoke the read? Or anything else on the callback to sign that the IRQ should not be cleared?

Sorry for being such a pester, I really counted on I2C to work in both directions and encountering all these issues is a huge disappointment about using the picos for my project.

**Comment by vmilea** [comment]
Turns out the behavior is not as I described in #2. After the first `RD_REQ`, the interrupt is cleared so you only get one callback. This is fine in practice, as long as you keep track of the request and write the data when ready.

Let's continue the discussion in #2.
